### ISSUE TITLE
App store

### ISSUE THREAD

**Issue by MP0w** [zats/Crash-Manager#3]
Why it's not available worldwide in the AppStore? AppStore ask me to change the store from Italian to Israeli .

**Comment by zats** [comment]
I took the application down since I don't have the time to maintain the app. Feel free to install it from the sources, it should be straight forward after you instal cocoapods: `$ pod install` from the project folder

Sorry for the inconvenience

**Comment by MP0w** [comment]
I already installed.. It seems perfect, for that I didn't understood the reason, thanks.
